package com.map.pandora;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.map.pandora.PoiHistory;

import com.map.pandora.PoiHistoryDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig poiHistoryDaoConfig;

    private final PoiHistoryDao poiHistoryDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        poiHistoryDaoConfig = daoConfigMap.get(PoiHistoryDao.class).clone();
        poiHistoryDaoConfig.initIdentityScope(type);

        poiHistoryDao = new PoiHistoryDao(poiHistoryDaoConfig, this);

        registerDao(PoiHistory.class, poiHistoryDao);
    }
    
    public void clear() {
        poiHistoryDaoConfig.getIdentityScope().clear();
    }

    public PoiHistoryDao getPoiHistoryDao() {
        return poiHistoryDao;
    }

}
