package com.map.pandora;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table POI_HISTORY.
 */
public class PoiHistory {

    private String key;
    private String city;
    private String district;
    private java.util.Date timestamp;

    public PoiHistory() {
    }

    public PoiHistory(String key) {
        this.key = key;
    }

    public PoiHistory(String key, String city, String district, java.util.Date timestamp) {
        this.key = key;
        this.city = city;
        this.district = district;
        this.timestamp = timestamp;
    }

    public String getKey() {
        return key;
    }

    public void setKey(String key) {
        this.key = key;
    }

    public String getCity() {
        return city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public String getDistrict() {
        return district;
    }

    public void setDistrict(String district) {
        this.district = district;
    }

    public java.util.Date getTimestamp() {
        return timestamp;
    }

    public void setTimestamp(java.util.Date timestamp) {
        this.timestamp = timestamp;
    }

}
